create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  phone text not null,
  address text not null,
  note text,
  total_amount numeric not null,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null,
  product_name text not null,
  price numeric not null,
  quantity integer not null,
  line_total numeric not null,
  created_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.contacts enable row level security;

drop policy if exists "public can insert orders" on public.orders;
create policy "public can insert orders"
on public.orders
for insert
to anon
with check (true);

drop policy if exists "public can insert order_items" on public.order_items;
create policy "public can insert order_items"
on public.order_items
for insert
to anon
with check (true);

drop policy if exists "public can insert contacts" on public.contacts;
create policy "public can insert contacts"
on public.contacts
for insert
to anon
with check (true);
